### ISSUE TITLE
Setup snoopdb to work as a kubernetes job

### ISSUE THREAD

**Issue by zachmandeville** [apisnoop/snoopDB#23]
Setup the db so that it can be run as part of a kubernetes job, whose success or failure is based on the contents of the db.

CONTEXT: We want to check if a k8s release has untested endpoints _before_ its released.  This is trivial to do with snoopdb.  If we create a k8s job that checks the db for untested endpoints from this release, and passes if there are none and otherwise fails.

To do this, we need to make it so the snoopdb container exits, with either exit status 0 or 1, for pass and fail respectively.

## Iterations

- [ ] add customized docker-entrypoint.sh to our container, that is designed to exit instead of continue running.
- [ ] customize this entrypoint to pass or fail based on presence of SNOOP_FORCE_FAIL variable
- [ ] customize kubernetes job to pass variable to toggle between PASS and FAIL
- [ ] customize entrypoint to pass fail depending on list of untested endpoints (we'd expect, without change, for it to pass continually)
- [ ] customize dockerfile and db init funtions cto handle env var that passes in a custom bucket/job to choose from
- [ ] pass a bucket/job with known untested endpoints, to ensure that the job fails as expected.

**Comment by hh** [comment]
About right, thanks @zachmandeville

**Comment by zachmandeville** [comment]
implemented with https://github.com/apisnoop/snoopDB/commit/514571272450ef03ee745a9083ee0aef17f6b465
